

/* SDIO Control Status Register */
#define MCR_SDIOCSR			0x0018

#define SDIOCSR_MAX_TXSTATUS_PKT_MASK	0xf00000
#define SDIOCSR_MAX_TXSTATUS_PKT_SHIFT	20
#define SDIOCSR_MAX_RECEIVE_PKT_MASK	0x0f0000
#define SDIOCSR_MAX_RECEIVE_PKT_SHIFT	16
#define SDIOCSR_FUN_MODE		(1 << 2)
#define SDIOCSR_SDIO_ABORT		(1 << 1)
