#libertas-y += cfg.o
#libertas-y += cmd.o
#libertas-y += cmdresp.o
#libertas-y += debugfs.o
#libertas-y += ethtool.o
#libertas-y += main.o
#libertas-y += rx.o
#libertas-y += tx.o

mt592x_spi-objs += if_spi.o

#obj-$(CONFIG_MT592X)     += mt592x.o
obj-$(CONFIG_MT592X_SPI) += mt592x_spi.o
